#!/usr/bin/env python3
"""Generate per-harness adapters from one source (Portable layer step 3).

Emits thin, host-specific instruction files and MCP-registration snippets so the same suite
runs on Claude Code, Codex/opencode/Cursor/Amp (AGENTS.md), and Gemini CLI — all built from the
registry manifests + skills/INDEX.json, so there is a single source of truth and no per-tool
forks.

Outputs (under portable/):
  portable/CLAUDE.md            instruction adapter for Claude Code (native skills + MCP)
  portable/AGENTS.md            instruction adapter for Codex/opencode/Cursor/Amp (MCP)
  portable/GEMINI.md            instruction adapter for Gemini CLI (MCP)
  portable/mcp/claude.mcp.json  server registration for Claude Code / Cursor
  portable/mcp/codex.config.toml server registration for Codex
  portable/mcp/gemini.settings.json server registration for Gemini CLI

Copy the relevant instruction file to your target project root and register the MCP servers
with the matching snippet.

Usage:
  python scripts/gen_adapters.py            # write portable/*
  python scripts/gen_adapters.py --check     # exit 1 if any output is stale (CI gate)
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
REGISTRY_DIR = REPO / "registry"
INDEX_PATH = REPO / "skills" / "INDEX.json"
OUT_DIR = REPO / "portable"

HOSTS = {
    "claude": {
        "file": "CLAUDE.md", "label": "Claude Code", "native_skills": True,
        "reg": "Register the servers with `claude mcp add` or a project `.mcp.json` "
               "(see `portable/mcp/claude.mcp.json`).",
    },
    "agents": {
        "file": "AGENTS.md", "label": "Codex / opencode / Cursor / Amp", "native_skills": False,
        "reg": "Register the servers in your host's MCP config "
               "(Codex: `portable/mcp/codex.config.toml`; Cursor: `portable/mcp/claude.mcp.json`).",
    },
    "gemini": {
        "file": "GEMINI.md", "label": "Gemini CLI", "native_skills": False,
        "reg": "Register the servers in `.gemini/settings.json` "
               "(see `portable/mcp/gemini.settings.json`).",
    },
}


def load_registry() -> list[dict]:
    out = []
    for jf in sorted(REGISTRY_DIR.glob("*.json")):
        out.append(json.loads(jf.read_text(encoding="utf-8")))
    return out


def load_index() -> list[dict]:
    return json.loads(INDEX_PATH.read_text(encoding="utf-8")).get("skills", [])


def build_instruction(host_key: str, registry: list[dict], skills: list[dict]) -> str:
    h = HOSTS[host_key]
    native = [s for s in skills if not s.get("vendored")]
    L: list[str] = []
    L.append(f"# AS agent suite — {h['label']} adapter")
    L.append("")
    L.append("> Generated by `scripts/gen_adapters.py` from `registry/*.json` + "
             "`skills/INDEX.json`. Do not edit by hand — edit the source and regenerate.")
    L.append("")
    L.append("This project runs the **AS agent suite**: a set of specialist agents that call "
             "**skills** (self-contained capability packs) on demand. Skills are loaded lazily "
             "to keep context small.")
    L.append("")

    # --- Agents ---
    L.append("## Agents")
    L.append("")
    L.append("| Agent | Use for | Owns skills |")
    L.append("|---|---|---|")
    for m in sorted(registry, key=lambda r: r["agent"]):
        when = (m.get("when_to_use") or m.get("summary", "")).replace("|", "/")
        if len(when) > 90:
            when = when[:87] + "..."
        owned = ", ".join(m.get("skills", [])) or "—"
        L.append(f"| **{m['agent']}** | {when} | {owned} |")
    L.append("")

    # --- Skill loading protocol ---
    L.append("## Using skills (lazy loading)")
    L.append("")
    if h["native_skills"]:
        L.append("Skills live in `skills/<name>/SKILL.md` and are available **natively** "
                 "(auto-activated by their description) *and* via the `as-skills` MCP server. "
                 "Prefer native activation; use the MCP tools when you want to scan or fetch "
                 "explicitly.")
    else:
        L.append("Skills are served by the **`as-skills` MCP server**. Do not preload them — "
                 "load only what a task needs:")
    L.append("")
    L.append("1. **Scan the directory** — `skill_list(agent?)` returns "
             "`{name, description, owner_agent}` for each skill (optionally scoped to one "
             "agent). This is the cheap always-on index.")
    L.append("2. **Load on demand** — when a skill's `description` matches the task, call "
             "`skill_get(name)` to pull its full `SKILL.md` into context.")
    L.append("3. **Deep detail** — call `skill_get_reference(name, path)` only for a specific "
             "`references/` or `assets/` file when that phase needs it.")
    L.append("")
    L.append(f"{h['reg']}")
    L.append("")

    # --- Skill directory (compact) ---
    L.append("## Skill directory")
    L.append("")
    L.append("| Skill | Owner | For |")
    L.append("|---|---|---|")
    for s in sorted(native, key=lambda x: x["name"]):
        desc = (s.get("description") or "").replace("|", "/")
        if len(desc) > 100:
            desc = desc[:97] + "..."
        L.append(f"| `{s['name']}` | {s.get('owner_agent') or '—'} | {desc} |")
    L.append("")
    vendored = [s for s in skills if s.get("vendored")]
    if vendored:
        L.append(f"Plus {len(vendored)} vendored anthropics skills "
                 f"({', '.join('`'+s['name']+'`' for s in sorted(vendored, key=lambda x: x['name']))}) "
                 "— same lazy-load protocol.")
        L.append("")

    # --- Contracts ---
    L.append("## Typed contracts (quality floor)")
    L.append("")
    L.append("Every seam is a JSON-Schema contract in `immortals/contracts/schemas/` "
             "(`registry/v1`, `plan/v1`, `artifact/v1`, `event/v1`). Validate artifacts against "
             "them regardless of the underlying model — this is what keeps output correct when "
             "the host or model changes.")
    L.append("")
    return "\n".join(L) + "\n"


def build_mcp_configs() -> dict[str, str]:
    servers = {
        "as-skills": {"command": "python", "args": ["-m", "immortals.skills_mcp"]},
        "as-memory": {"command": "python", "args": ["-m", "immortals.memory.mcp_server"]},
    }
    claude = json.dumps({"mcpServers": servers}, indent=2) + "\n"
    gemini = json.dumps({"mcpServers": servers}, indent=2) + "\n"
    toml_lines = ["# Codex MCP registration — add to ~/.codex/config.toml", ""]
    for name, cfg in servers.items():
        toml_lines.append(f"[mcp_servers.{name}]")
        toml_lines.append(f'command = "{cfg["command"]}"')
        args = ", ".join(f'"{a}"' for a in cfg["args"])
        toml_lines.append(f"args = [{args}]")
        toml_lines.append("")
    return {
        "mcp/claude.mcp.json": claude,
        "mcp/gemini.settings.json": gemini,
        "mcp/codex.config.toml": "\n".join(toml_lines),
    }


def build_all() -> dict[str, str]:
    registry = load_registry()
    skills = load_index()
    files: dict[str, str] = {}
    for key, h in HOSTS.items():
        files[h["file"]] = build_instruction(key, registry, skills)
    files.update(build_mcp_configs())
    return files


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="exit 1 if any output is stale")
    args = ap.parse_args()

    files = build_all()
    if args.check:
        stale = []
        for rel, content in files.items():
            p = OUT_DIR / rel
            if not p.exists() or p.read_text(encoding="utf-8") != content:
                stale.append(rel)
        if stale:
            print(f"portable/ adapters stale: {stale} — run: python scripts/gen_adapters.py")
            return 1
        print(f"portable/ adapters up to date ({len(files)} files).")
        return 0

    for rel, content in files.items():
        p = OUT_DIR / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(content, encoding="utf-8")
    print(f"Wrote {len(files)} files under {OUT_DIR.relative_to(REPO)}/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
